### ISSUE TITLE
Exception after several hours

### ISSUE THREAD

**Issue by jbobzin-insyde** [DMTF/Redfish-Service-Conformance-Check#29] opened 2017-09-01 20:15 UTC
Using the 8/31 code, had exception below

---> Assertion: 6.5.17

Expected property @odata.id in response body

Expected property @odata.id in response body

Expected property @odata.id in response body

Assertion Description: Resources in a response shall include a unique identifier property named "@odata.id". The value of the identifier property shall be the unique identifier for the resource.
 <--- Assertion 6.5.17: FAIL

---> Assertion: 6.5.18

Traceback (most recent call last):
 File ".\rf_client.py", line 780, in 
 main()
 File ".\rf_client.py", line 774, in main
 rfs_test.run(sut)
 File "G:_Redfish_git\Tools\Redfish-Service-Conformance\Redfish-Service-Conformance-Check\rfs_test_init_.py", line 39, in run
 TEST_protocol_details.run(sut, log)
 File "G:_Redfish_git\Tools\Redfish-Service-Conformance\Redfish-Service-Conformance-Check\rfs_test\TEST_protocol_details.py", line 5040, in run
 assertion_status = Assertion_6_5_18(self, log)
 File "G:_Redfish_git\Tools\Redfish-Service-Conformance\Redfish-Service-Conformance-Check\rfs_test\TEST_protocol_details.py", line 3570, in Assertion_6_5_18
 if(json_payload is not None and '@odata.type' in json_payload and isinstance(json_payload['@odata.type'],basestring)) :
 NameError: name 'basestring' is not defined

**Comment by peanutsandwich** [comment] 2017-09-01 20:17
Hi Jeff,

I contributed a PR recently that made this change for compatibility with Python 2, and it looks as though Python 3 removed the basestring type.

A solution for this would be to set 'basestring = str' or a try catch block around the offending code that catches the NameError and uses the alternative.

This would need to be done in the Python 3 branch at the top of the file.

I'm not going to be near a PC to be able to try and submit a commit for a little while, but will submit a change when I am able

**Comment by jbobzin-insyde** [comment] 2017-09-01 22:06
After temp patch (edit basestring to str in line above) the tool runs further but gets exception below

---> Assertion: 6.5.26

The namespace is EventService_v1.xml
The schema file has the same action name as in the response
The namespace is ComputerSystem_v1.xml
The schema file has the same action name as in the response
The namespace is LogService_v1.xml
The schema file has the same action name as in the response
The namespace is Manager_v1.xml
The schema file has the same action name as in the response
The namespace is LogService_v1.xml
The schema file has the same action name as in the response
Traceback (most recent call last):
  File "rf_client.py", line 780, in <module>
    main()
  File "rf_client.py", line 774, in main
    rfs_test.run(sut)
  File "G:\_Redfish_git\Tools\Redfish-Service-Conformance\Redfish-Service-Conformance-Check\rfs_test\__init__.py", line 39, in run
    TEST_protocol_details.run(sut, log)
  File "G:\_Redfish_git\Tools\Redfish-Service-Conformance\Redfish-Service-Conformance-Check\rfs_test\TEST_protocol_details.py", line 5050, in run
    assertion_status = Assertion_6_5_26(self, log)
  File "G:\_Redfish_git\Tools\Redfish-Service-Conformance\Redfish-Service-Conformance-Check\rfs_test\TEST_protocol_details.py", line 4220, in Assertion_6_5_26
    log.assertion_log(assertion_status, None)
  File "G:\_Redfish_git\Tools\Redfish-Service-Conformance\Redfish-Service-Conformance-Check\logger.py", line 448, in assertion_log
    print(log_string)
  File "C:\python35\lib\encodings\cp437.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2022' in position 203: character maps to <undefined>

**Comment by peanutsandwich** [comment] 2017-09-03 22:59
Hi Jeff,,

I have a fix in PR #22 that I submitted a few days ago for this. It is being caused by a unicode 'bullet point' character being in one of the assertion texts in the redfish-assertions.xlsx file.

The fix in the PR is to encode the assertion description as utf-8. If you could give that a go that'd be great. It is line 443 of logger.py that needs to change, and you need to change 
`log_string =  ('Assertion Description: %s\n<--- Assertion %s: %s\n' % (assertion_description, self.AssertionID, log_control))`
`log_string =  ('Assertion Description: %s\n<--- Assertion %s: %s\n' % (assertion_description.encode('utf-8'), self.AssertionID, log_control))`

Cheers,

Mark

**Comment by peanutsandwich** [comment] 2017-09-03 23:10
Just submitted PR #31 that should address the originally reported issue

**Comment by mraineri** [comment] 2017-09-07 21:49
Closing; should be fixed now. If not, please file a new issue.

**Closed by mraineri** 2017-09-07 21:49 UTC
